const settings = {
  ServiceAddress: 'https://m.damda.com',
  ImageAddress: 'https://m.damda.com',
  Intro: {
    close: 'Bỏ qua',
    logo: require('../assets/images/logo-intro.png'),
    textBtnLogin:'Đăng nhập',
    textBtnRegister:'Đăng ký',
    sliders: [
        {
            id: 1,
            image: require('../assets/images/intro/intro-1.png'),
            text:'Slider 1 Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat',
        },
        {
            id: 2,
            image: require('../assets/images/intro/intro-2.png'),
            text:'Slider 2  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat',
        },
        {
            id: 3,
            image: require('../assets/images/intro/intro-3.png'),
            text:'Slider 2  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat',
        },
    ],
  },
  ViewMore: 'Xem thêm',
  noProduct: 'Không có sản phẩm nào hiển thị',
  
  CourseNew: {
    categoryCode: 'new',
    page: 1,
    offsetRight: 15,
    ViewMore: 'Xem thêm',
    ImageSizeWidth: 155,
    ImageSizeHeight: 120,
    noCategory: 'xin vui lòng, hãy chọn lại categoryCode',
    noProduct: 'Không có sản phẩm nào hiển thị',
  },
  CourseHot: {
    categoryCode: 'hot',
    page: 1,
    offsetRight: 15,
    ViewMore: 'Xem thêm',
    ImageSizeWidth: 155,
    ImageSizeHeight: 120,
    noCategory: 'xin vui lòng, hãy chọn lại categoryCode',
    noProduct: 'Không có sản phẩm nào hiển thị',
  },
  Lop1: {
    categoryCode: '1',
    page: 1,
    offsetRight: 15,
    ViewMore: 'Xem thêm',
    ImageSizeWidth: 245,
    ImageSizeHeight: 180,
    noCategory: 'xin vui lòng, hãy chọn lại categoryCode',
    noProduct: 'Không có sản phẩm nào hiển thị',
  },
  Lop2: {
    categoryCode: '2',
    page: 1,
    offsetRight: 15,
    ViewMore: 'Xem thêm',
    ImageSizeWidth: 245,
    ImageSizeHeight: 180,
    noCategory: 'xin vui lòng, hãy chọn lại categoryCode',
    noProduct: 'Không có sản phẩm nào hiển thị',
  },
  Lop3: {
    categoryCode: '3',
    page: 1,
    offsetRight: 15,
    ViewMore: 'Xem thêm',
    ImageSizeWidth: 245,
    ImageSizeHeight: 180,
    noCategory: 'xin vui lòng, hãy chọn lại categoryCode',
    noProduct: 'Không có sản phẩm nào hiển thị',
  },
  Lop4: {
    categoryCode: '4',
    page: 1,
    offsetRight: 15,
    ViewMore: 'Xem thêm',
    ImageSizeWidth: 245,
    ImageSizeHeight: 180,
    noCategory: 'xin vui lòng, hãy chọn lại categoryCode',
    noProduct: 'Không có sản phẩm nào hiển thị',
  },
  Lop5: {
    categoryCode: '5',
    page: 1,
    offsetRight: 15,
    ViewMore: 'Xem thêm',
    ImageSizeWidth: 245,
    ImageSizeHeight: 180,
    noCategory: 'xin vui lòng, hãy chọn lại categoryCode',
    noProduct: 'Không có sản phẩm nào hiển thị',
  },
};

export default settings;
